### PR TITLE
Rename package to circuits_gpio/Circuits.GPIO

### PR DESCRIPTION
**Pull request by fhunleth**
This seems to be the best option for easy to type and not too generic.

I also added back the NIF checking code so that it's possible to build docs on OSX.

### CODE REVIEW

**Comment by mdsebald** [comment]
I'm not sure the NIF checking code works.  If "nif_binary" path and filename does not include the ".so" file extension then File.exists?() would always fail?  Sorry can't verify this, where I am right now.

**Comment by fhunleth** [comment]
I removed the NIF check code out of this PR.

**Comment by fhunleth** [comment]
@mdsebald Are you ok with this now?

**Comment by fhunleth** [comment]
Thanks!

**Pull request merged**
